# version: '3'
# services:
#  nginx:
#    image: nginx
#    ports:
#      - 60080:80
#    volumes:
#      - ./:/usr/share/nginx/html/

version: "3"
services:
  nginx:
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      - ./:/usr/share/nginx/html/
